#----------------------------------------------------------------------
# This file was generated by encode_bitmaps.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

testimage = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAHFJ"
    b"REFUWIXt1jsKgDAQRdF7xY25cpcWC60kioI6Fm/ahHBCMh+BRmGMnAgEWnvPpzK8dvrFCCCA"
    b"coD8og4c5Lr6WB3Q3l1TBwLYPuF3YS1gn1HphgEEEABcKERrGy0E3B0HFJg7C1N/f/kTBBBA"
    b"+Vi+AMkgFEvBPD17AAAAAElFTkSuQmCC")

# ***************** Catalog starts here *******************

catalog = {}
index = []

#----------------------------------------------------------------------
book = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAhBJ"
    b"REFUOI2lk89LVFEUxz8Td8yGnBmTsnSKfviIRGph7QZCIYNoIfQvuGoTtGoVtGrfxkULF0E7"
    b"F0IFtol2FhqSbVQEbRYFI4SvUXz3nPNui+c8FKaVZ3nO/X7P55x7LxwzCgBTrxdG84yAIIgI"
    b"b5+MLwFMvnw3KpLlRATZE0T2+DL9eKmQiQuLl/pKpKlhlpKakXhh6/efm957BvtOfycYqoqK"
    b"oKr82PhFsXTqtgtpukjhBM8eXs8h0jRl/tsWqz+b86bKvVs1Hty5egR9dOoVXcXiogMwMwBW"
    b"VlYwyzqNjYxw5Yy70NNT5mJ/L8vLy5gZrVaLer2O9wniu3AAqgpAFEWYGSJCo9GgsbnJ8PAw"
    b"SVIiiiJEhDiOAfBJgj/ZhQsBVASAtbU10jRFRKhUKsRxTJIkeU1VabVaDAwM4L1HvMelpsiB"
    b"QRRF2aJUaTabhBDymYeGhlBVdnZ2ssvyHhHBqSriPSEE1tfX8x2Uy+Vc3K61CWq1WmbgDxkc"
    b"JvDes729TQghp2gTtHcgIqh4nEomAOju7s47lkolqtUq1WoV5xzFYvGIYXtUJ+LxScLdpzOI"
    b"F0R8jjdZv0EIgTcfFrKOqtiB0MxQUZyIcHnwbMd3Pvv5KyrK/YmxjvW5ufe4/f19NuO/B52P"
    b"EpzvP4eZMf/xU0eC1Cz7TJ3i2qMXM7u7rXFTpVzpXd2YfT7xv7PHin/ZG4/t2teD9QAAAABJ"
    b"RU5ErkJggg==")
index.append('book')
catalog['book'] = book

#----------------------------------------------------------------------
clipboard = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAf5J"
    b"REFUOI2tkUFLVFEYhp977h1znAnSCRKbEaGwNgZF0K4gV22iP9Am6Dc0ENU2cKFCtKtlq+gX"
    b"ZLRqIS2MiNAkyKLSgZm8jV7vnPN9X4vJQRlrU9/ucM778HzvgX+c6E8Xs7Ozp8rl8lMzk2az"
    b"ebVer6/9FeAfTE1z5Ph9xU02pBI3T14vlkZPuEKhQHN1UY68f7gz4r+JBVayfKs+enttASDp"
    b"oSq1GVepnE2OllluXOHShct47wEYG7sWv8yT0rQ8Jmxn58PnjzPAuX0A0WgyGSnz6PUUb989"
    b"59XiG0QEAOccjY0Gn05f5Eb1BZLb5G6uB7CgIJ7iUIm5ufl9e4pACHD3Th1qEUECfQA1hRAw"
    b"U9rtwOrqNnGckKbrbG5+pVqtYgao4n+b7Qd0chCPqlEuJ4yPHyKKHHl+jCwbZnDw8K4rqgcB"
    b"VByimBmtlrC0lDEwUKDdXidNvzAxUeuFvA/W34HsRISAiCGiOJdjJjinxDFEkQMMRFEV7Tfw"
    b"HkQwM7LMk6bfKRQSvN+i0/lJp9PZVcVrL7+3xEDXIMK5IYaHS8SxI4SEYjGhVKp0SzRD9YBf"
    b"IHQNyFvMz93qPt4zZlCrlLqWcpBBCCv5ZnrmZnUBahGo0qOo9s6tjQZm9qEPsJX+uBc0PFOx"
    b"yEzAjKCKiBJECCKICEHDMlnnCf9rfgG9Rixh8s0DuQAAAABJRU5ErkJggg==")
index.append('clipboard')
catalog['clipboard'] = clipboard

#----------------------------------------------------------------------
code = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAw9J"
    b"REFUOI1V001oXFUYxvH/OXPv3MxMnJlOk6atQR0XdmGtVNCYRYyg1YXgVkuL1HShC4VQW4La"
    b"nR+LFqEoSoIbwRaKFEQkRYwupBG1kAoumqih1U4bms6Mkzsf9+vcc46LmqE+8Gx/vPDyCP7L"
    b"S19ce0xIe+r+cm48UIZAGZQxBKnxhbUdK2gIhMbSAppI87nXaHzrbALWpGN7tg2OvzE5zJ3p"
    b"JaYUJKbUivRooqATa/5qdDm/2t0XFivTfUCn6UgxKwCobWhcIXAEZBzwXMk9niQjJW4G9o7m"
    b"2FkqVD795cYHsg8kqlg2EamBTiLwFbTbEX4EfgTNEG51NQBvnrnGeLXA7uHscB8YDDdGnvhq"
    b"jvTlQ/QiTfXEDEOffUTg9+jEhm5kCRMwgNBtfr7SYulvf00C2MOHKzNLZ58tOCFKOASxReHg"
    b"0mH73EmiVodebOgpAxbW2zGnFlbbOlGHZHzw4Ithu3Njxza3ZGpNakffJQUu7Z8mue6TFT0e"
    b"ODqFt/gDUSowFrSrceK0+uXrjy5IHUZzydjuAXNpBY7N0B6sICToYoU/X3gNfv0dNfYgd8+e"
    b"QCqFtZDGMS3V0wCSKHxFnl+MTHUn4vjb2Ft1JJas36A6+x7pfTsQ84vUpqYRWRelNd1eL/1u"
    b"5uk2gMzPz5+dHZ0cu7K6gRr0qB6ZAgu73j9GpugQtAyXZ8/hT+wj50KzG5PGyTpC2NsXAPND"
    b"u5IPJw7gxJCp10FIZKNO4MPV4ydRhRJYyDuSeitEJ8na5vecySNnhtI0euehPXvpTp/m++WE"
    b"Qkfz0ydfM+BaXAeymdst5mG1FqCSeL0PRGH8lLT2uaXlq7RCh25sUdoSK0GSGlJtMNZSKZV4"
    b"9Znt3GwG6FjV+4BRySPPP/lw7q0Dj/9vA9qC0pYkBSx8/M0aeRc63QCdJs07AHX1ZsPn9MIy"
    b"5cEc5eIA5YJHqeBxVz6Ll5V4jmT/xAieA/V/OuhEXe8DJPG5CxdXRi9cXL5XCLEV2Ap2i0Vs"
    b"wdpSzsu6AwMuxUKOcjHPbyu1P8iYHzeBfwEwiol55ANRRAAAAABJRU5ErkJggg==")
index.append('code')
catalog['code'] = code

#----------------------------------------------------------------------
core = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAmJJ"
    b"REFUOI2lkk1LG1EYhZ+ZuQljPsSQkFAwbbMICKnQRXfRRegvEALG7uxPKbjJVuii9AdM3LpQ"
    b"F+4rLUERi1QUP5MRgwmaxNzJzZ0urCGpiy569ud5z3k5huM4Pv8hAZBIJLi5uSEWiyGEYHNz"
    b"k42NDbrdLq1Wi06ng+8/3TFQqk86naZcLmM4juMXCgXa7TZKKbTW9Ho9pJQopZBSorXG9w36"
    b"CnzdQWuDqakparXaY4JkMkkymRyL5vs+vu9jGAbdbg+tGkSsn6C6DCJFhBBUKpVHwKju7u64"
    b"vb1FKUWz2eTs7IzvP3Z59ybE21yKF6/yqHaXQMACwBw1NxoNTk9PkVLSbDa5vr7m5OSEr18+"
    b"8+HjJ365rwlEsvT7cvyJAFJK9vb2sCyLer1OrVajXq9zfn6O1++j+pLd6jfeF/L4vo9pmuOA"
    b"w8NDdnZ2ME2Ti4sLXNfl8vKS4+Nj2u02AGtraywvL2PbNpZljQOurq5wHId0Oo3ruriuS6PR"
    b"wPO8x66mycPDA0ophBDPE8TjcY6Ojtjf38c0TbTWAASDQSYnJwmFQmQyGSYmJjAMYwgwAQaD"
    b"AbOzsxSLRQC01gQCARKJBJlMhmw2SzQaZWFhgXA4PNzGMIFhGAghKJfLuK7L9vY28XicVCqF"
    b"bdtorVlaWiIWi7G+vv58yk+RhRCsrKwwPz/PwcEBANFolHw+z9zcHNVqlcXFRQAqlQqlUiky"
    b"NqRwOMzMzAy5XA4pJZ7nEQqFCAaD3N/fA9Bqtdja2qJUKtmAHAJs2+Zv2KienvbHbIxVWF1d"
    b"rXue15+enn7JPzRqBvgN0r4cgCHFMd4AAAAASUVORK5CYII=")
index.append('core')
catalog['core'] = core

#----------------------------------------------------------------------
custom = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAvpJ"
    b"REFUOI2lk19MlXUcxj+/933PezwvdF4OCBxg5g4cp9IQDHQsxWq6YsNlUW7pNKYXtLm5vGhz"
    b"y7zLorpwja0CabU2HVt1YUuT/jAxU0eaOEUMEUqSIxzOOXA4vH/Ov7c7Jce66bl7novPvnv2"
    b"fOF/Sjwa7Fu39HBFQeagLDs5yYxD3BbG6Kzr6Infw28vBpAXmtZa38GqUucd7TGhKm6BJAvA"
    b"cQnSDQXeXOn2lHn2UYC00Kz1Z9s0TYhYPEN0LkPCgqykosiK8LlSBxa74F+AmbkMJU/vY+f+"
    b"Qzz70l5C8woRS8FQ8tA8suej/Y3u/+ygc/fyyO4Pf8hP3uklYZhMR2fx5mrolVvoadser2vM"
    b"b80YwW45t4r56T6w7rUoCwFmVhsy717ZkHYvxZeTxldYSiItQ3QYfZkaydU3d3sqGtADa5kZ"
    b"W8lQT9cHD0us7XDdSSzZ9Hj4m+qamipQvQhJQXUsrvzURk1Ts+4rqxdzE7eQkwaat5jZyT8V"
    b"ARBsPO2OEdvrofjjM531DHbsxMEBIN83T13jBvTy57FD3ZgRwdQfBknTjlh24ikZHJEKDOzS"
    b"1WXHejrXc1VoXF6xg5HyHWRLSnihxkYPbsWa6ERSDaCI1Mi1SdOwnqt74/Sgsrr5i21lUvjz"
    b"199s5lxEZtBwSFngv/8te4IX0YMvYt37BMmVJhkPMP7zb3x2Y9WnR491DABIxyvf//pES5TJ"
    b"m99zaQKMmKDw71O87LtA0RNNJO93IasOdnw5ob7LFAWq2a73vfVgB5IQkuLWOH9pmqBi4Bvp"
    b"5tWCi2SdUkLX28liMR8t4+4vtzhydRsuzYssS8pDwIoth8Z6v0wvSYbSJ4/3s97sonJjK+7x"
    b"8wyf/JWBnij9Z65xoLeJPGfcGD33le2p3HzkAWDNa+3vafWb8v1+/FMziY6h21MkB78jUN1A"
    b"Ts5KxvqHeffsM7G/UkU/qi41oD1ZV7impf3woksEeGVjnllbUaysW12O47Iv2OHwnq1t10cX"
    b"+wOAfwAJ9yQGhieeeAAAAABJRU5ErkJggg==")
index.append('custom')
catalog['custom'] = custom

#----------------------------------------------------------------------
deleteperspective = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAnpJ"
    b"REFUOI2Fk0tIVVEUhr+9z9nnmrc0095RVIJSCNFAGkiEFDXIRk6aNCkIoiALIiKiJpZBEyuK"
    b"GkQIEUhCCGVQg8pKJJWil/nonXY1vd6Hj3PuOatB96aV1IIN/2Ctf63//9mqufXlYF7OzJAv"
    b"QqYCgYkxF8/zGBiKat8NhqOx0S27dmx+wZ/1tKNrLAgCmfp835fkmCexuCcdz3ulq6dPmu62"
    b"D1yuu73hz3n9FyOglEJrUDpAW5oFCwvYUFZSUFS47M61Gw8q/0sggAIcx+bd+0+0tLTT9uwV"
    b"fmrcScSi9UePn6v6JwGA0gqtYG7BHNxA8a1/hO6eTzhZDvHESHWmz552GNBKkfJSlKwpxh33"
    b"GIxPMNTXhzEOrS3N00gIfHjdCp1tBEBKIGUMid5e9OkDmHsNmOwwjmOw9OTeSfT5LTxpgmQU"
    b"+dhLsqwS+dBJXu0RQveamLH0Md7qUvS8xSjFNAQLV8KyIrjbgNV5hfDTR+jubszD+3iLVjC8"
    b"9wRWwXyMCtIiMwRpPK5t1PpK1OgE5vpFQi8bITKMt2oNQ8fO4y0vxkoksGwbNeUEO2NCygdl"
    b"LGydhfoSga8DEB+HL99RgUI5BkuBpTJBp00MMs57Lk7dWUI1h2FgBH/tOoJwPqbtDflbNxG6"
    b"1QgzstPbJy/4lYLd3IQ5fwr6B3G37yR+9Q7JM5eQnFysSITZB/ehI/2IcX6LfFJCaTmqfBuy"
    b"pBB3VxUigldRQbT+JtmH9pPcvYdgVi6Wl/pNgh2kcTgvB05eQAAD+D6IgL9xPW5HO8oTwkkX"
    b"2zZMzdEeiceT1TW1Ka0NP+3xUViI+IiApH+GiIAISmmSsdhEhuAH7okWfiVuCWIAAAAASUVO"
    b"RK5CYII=")
index.append('deleteperspective')
catalog['deleteperspective'] = deleteperspective

#----------------------------------------------------------------------
demo = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAuZJ"
    b"REFUOI2lk0tPYwUARs9te7l9pDCEPmCGkQ6FlostwlCKCk5MGFw4asDEmBg2Jv4B1vMDZONa"
    b"F5MMW6LRhWhmYWYzwvAsj2mTYkcqhZa+L7X0cft0OwsXk8xZf/lW58AbIrzGRj8+Pj7o8/ne"
    b"uXdv9r1cTiktLy8/BFr/e9Df339rampq1O/3TU1M3PUNDDi8JpN5QK21xVpNZVR2IsuyNxwO"
    b"BwF0w8PDg/Pz83Ozs9N+r8czYbX2DjXbuq5kpsJ1IUkicUmpkiRfMpFIpOjr7WFhYeHByspK"
    b"EEBYW1v748Enn86tP9kjGM4QT6kIooXJt0184Ldhtd1C1GmoVss82z7DeqNJp6m25fe/PwO0"
    b"NKenL5PxeJKH3z5l9ccoh+EGoqjHK1uotuycXTaIXqhkFJBdb3GZLjEyIk86nU4ZQGswGPuW"
    b"vvri493DS7JKg2arib27jMncSyzZJpnKUShWySkq2ZxCJltk6I5F+28h98/m5vNNbbVaFZeW"
    b"vvw6kSoLhyGFZqOGpC1wXdaRzLbpNOupVK5JJBVSqSy/PjlC39Fi7sMx06NHjx9rYrHYyelp"
    b"9HJs1I5eMnL7tpNqy06v1cBNmw67xcC4dxDZ1YcoXFMsi+wcxHG7R3wul8utAXJ7+8ehYYeV"
    b"HkeRtlik54aHeK4TS7eRmzYd3eYajUqCZiXCRzMi05P9mExdHYuLi59rAAKBwF63WUQed3I1"
    b"s0He8RtdRg3FUoXIyzP29wOYjS3enb5L5vwZumaUi4sLJZ1OCwKAx+NZ+PmntV9enGj50/w7"
    b"Y2YH7roHq02i0yyh0YCiKI1A4Ci6urr6dyQSuV+v15/GYrHPBABJkobW19ePBwfvGCSMIDTI"
    b"FFKcnPx1vrsbeLGzs/M8FApt5/P5IJCRJOkbvV7/faFQ+E4HoKpqbGNj4+DqShnZ2to+Ojg4"
    b"2A4Gg1vpdPoYOAcar+ququoP9Xq9QxAEy6stuIEOIAJUXzPGN+c/irhDxtglzjIAAAAASUVO"
    b"RK5CYII=")
index.append('demo')
catalog['demo'] = demo

#----------------------------------------------------------------------
dialog = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAJ5J"
    b"REFUOI2tk1EOgjAQRN8ULkXizSrRkHoySHus9cMULQJa8f1sMtmdTnZTyTUcQWEI9utwf72o"
    b"BfC9R7p9PWjmkYRcgwOqhpf9bXasRToDPBJk0pSqKgBhCGZmFsdYVQGTa54GtSZvBn9J8Aow"
    b"N6/p2WBe4tqCulO3qRdnzKKk4lRpSpt6pkhgZsQxzjUnWNOLBMsXatDR3+g+t+xzB+jeEF9n"
    b"B4s2AAAAAElFTkSuQmCC")
index.append('dialog')
catalog['dialog'] = dialog

#----------------------------------------------------------------------
exit = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAthJ"
    b"REFUOI2lk91vU3UYxz/nre26ttkGpZvdWJ0LkF3AhWSijMQoaEKMLwn/gqIJAYyaQLwwxmAm"
    b"S9BLLzSazBhRYBqXErKEYTJggwwYvgADRgPr1rOenb31nLZn53d+XhibSORGv5dP8nzyPM/3"
    b"+cL/lPJw4SvYpGvKgUQm80p9e/vawPdZyOXswsxstuyLTw/Br48EfA17W7ufPLZx//5o83PP"
    b"YxUKBHMWSemTPzfM2KkB/8btqfeBYx+CD6D93dwPezftefXzp7/9zmjY9gylhUUmxy5j2zb1"
    b"5QrpJzrZ0Namera1617BdEbgfG2Cfuhq7t46/uzgYERPprAnJijncshkEgm4AwPUS0k8kESX"
    b"bL45fVpcnzW7P4Mr6l+LKPu63nk7oidT3Dl5ktz4OPlLl1B8H9XzKObzWFu2cGfqLsK02P5Y"
    b"WtNV5TCAChBPp15LeUUWhs8QqBqdO3dCfhpWV1GEQE5Pk+npofH1N5j67Tp6UKEhFtsFoANE"
    b"081rguwJCvdWaP5xCOvE96TXJNEjEdA0WkoO5ie9tB7t42JDE9EHU8RDRqwGCAJJtVRGiYSQ"
    b"noe4PIoqA6o3bgES6S5TGR1FlF1CmQzVyd8RkSg1wKK9uFB9fP06LV9Ea2zAt2zun8kihn7C"
    b"XwVn3qFp+w70WAJpmkhFZanqubUbFPNm1lJj6PNzeCMXSB3pxUilqcw6uJZDfdNaOvr6qN78"
    b"A3fiCm5dmJlK9ZeajUdhc3vXhvGeznV6aXKGllNZRDyKM/AzUggSL7+EEQpxbfduqrnbjKEG"
    b"V1ecHcfhggYwBObm4rwr400vtCR0lr/4EsOoo27bU4TbWqmcO8vdt96kcj/HLd3g4nLpyHHo"
    b"/8crfwC6B+92dLR/vDEWUhJzFroICHzBilOmaBjcVFSuldzeEnw0CO6/hukgbDXC4fcaw6EX"
    b"w4qMCSFYEtI1V73hJT/o+wFGHp3N/6A/AcbQQIv/cYpDAAAAAElFTkSuQmCC")
index.append('exit')
catalog['exit'] = exit

#----------------------------------------------------------------------
expansion = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAlhJ"
    b"REFUOI2VkjtrXVcQhb/9uPdcS4okSyCQwSkCEqRwogRsFzaCgGzsVk4d0qQQpE+RPj8ivZpA"
    b"qrhKcws3TiOnMNgqLGxDGgkhoat7HnvvmUlxpCiPKl+zGZhZzJq13a0f3v66fL36IicjTQup"
    b"FlIjpLqQGyG1hdwKqRZynSmdol3BSoO178dxZWVu87P1pXh6CudnMJ3C5AymZ31tHrKAeEgK"
    b"mujxgD7djMuVy2tzVBMHeQ7OJ9AuQNNC20BTX7wNNFNIHaiBx9j/Pea4tmx8/QkcHR3z4sUe"
    b"W48eAGAAAXBgBppBiiIqaDGqAXz1vScGYOBh4ARJNdWAK45fQn0MzmErn6OjGUoxNBpVgIE3"
    b"IloAUDNCiPyd9udvkFe/QYD47TPs5j2kGKqGB4oYUbRvrqqKg4MDdnd36bqOjdv32Vhcpput"
    b"wAeMQBEwVUQUdaCmRMwAyDmzurrK1tYWZsa1mVnK6xmYWQAfEAKmhogiYhQMFSPahYCZMRwO"
    b"WVxcvKihfPlTn1YB7RKlqVHtLRQMMyOqGv/GDEpWZOgxIPs+Oi2GmKKqeLsQQPWvQeeuBGzg"
    b"sV924N1zQgjIwx+RpVtoN0XE8GqYcXUDgMnknMPDQ1LKVAtLfHC0j/3xEh8C1k5Q9Yj0FtQb"
    b"mBEv5+fn56lGI8bjMV2XWP/0Lrd9pmQBFUQFUVC1fgP6zWPo/xyj0Ygn29v/uEV2O7iPHmM4"
    b"qusfEqiRIKiHYTRicLg73+2dfHxjMNfVmZIKpU2UnCidIDYiF0dOCW1PQAuXhoN37L85Pf9P"
    b"Av+XPwHwQHwFXrN+IwAAAABJRU5ErkJggg==")
index.append('expansion')
catalog['expansion'] = expansion

#----------------------------------------------------------------------
find = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAtRJ"
    b"REFUOI1tk8FvFFUcxz/vzcyb2e7utMx2d1tbLCutuCExHDCKJCpRSDAGDkQPhGjiDbjoCf0P"
    b"9AInOTZKjCHhwkVJwNgQMcRYisJa6oaWggI17K7d7my309mZ56F2s2v4Jr/k977J75Nv3u89"
    b"wX+amiqllOfdzGcSo3Gsg00/0hCsI6o13y7Pl88cP/rWpzxNF6/dSd9ZqC7Fcay7qx3HutKI"
    b"9Uy5pmfKFT154dqZ7jnZfYi7eq01WmskoKwNb8izeXv/yx+d//bGWbQWAGY3wDQFa80W09Nl"
    b"gvUQp89maGgLQ1tHSKccZu8+IgKk6jt+6rOv3c/hWAdQmatS9ltcXlgkU9jGeGGUhCl4XG2w"
    b"9PcsYxPjZAezzC8+QmMihXwHeK4DuHLlUi4/OuzsOHCQ4hsFMhYowBnL82D2L+7fXSCZyeOm"
    b"k5gqga0sAcgOIAzWPgzcQn9qrEDtHwgToCSsaVhJDdN+WGNYrZBKpTGVjaksDegOIIqjFyst"
    b"l8oSWAH4yY1bbaxBzZckwiRjJjiOwlI2liF7t9D0V6t2vILXB/0KPBvSCmwNoi3QgY8UEsdW"
    b"JBwL0xC9gJV6/Zv6/C9tGS6zYxwmRqC4FZ4vQNZ4QiKqk/SyGKaJIUHI/yV4/b3914vbs9Uf"
    b"zk3y+89zCL+F8Fs8vP0H965fpemHcP8SYn0ZwwKxufpNwOFDhxlMmizeLvH9xcvcnHJxEg7e"
    b"QD8j+QxPpr8knatiBFeJdp1GmE4voFKt4Nk5Dhzcy2tvvkKt3kRriTuQYrWxzMyvJ9miMjgT"
    b"Fo3ZU4TNlzQQ9TzlzViOMngm6zKSS5FUMJgZYOeJ7/jtp2XCuRu4xT5elZPOqEuuk6A/9PTc"
    b"vT+bt0q34hgZaCCKQeuNEpbLUvYTSuc+Nt7Xsdqz+1lnT9E70gHs25f33/3gxN4LX50doPdf"
    b"dckOt6WjXLvy4xfrLxzbVVrd2fgXbJkZTtWGQBcAAAAASUVORK5CYII=")
index.append('find')
catalog['find'] = find

#----------------------------------------------------------------------
findnext = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAuVJ"
    b"REFUOI1tk0tsG1UUhr8Ze8bjPDzOuH6QOA/nUccqoBaBRNoKqPqQyiJdIFghENkgyooFahft"
    b"nlXEAthUiqCLqhIbxAKkFIgMilIgpdC6YCoaKlBFq9iJXY89M57HZdHYiqX+0pGO7uLTf85/"
    b"j8SOVlZKA6phXE8notkgEE7n3RcwdGFR9z1P/NOfuDp3/v2D7JLcaepKSDIGI4OTw7o2nY3r"
    b"nZoZjeue4xA9cEAax567eubctccCAIJdvRACIQQy4DWbCM9DHRtj2LOeWXvr7T8QQgII7waE"
    b"wxJ202J9/TZO20Xri5DJDBG2LALbxjNN1KkpktWfZr88+vKdeZjsAirlKrdNi+WNuyRyE0zn"
    b"skTDEv9VG2TqdXzbpl2tAqDm80w+eJD7NpO51wVcufJ1Kp19QsufOEnhpRwJBVRAG0/TrtUI"
    b"HAe/0UBSFCQgsCzavl/uAlzHXnBiOX1gPMfWNrhRUGWwBWg7DnbmZLtY5C8RcRc2N9/pAvzA"
    b"f7pixajcB8UBs//RVhs25Gs1PNNEUhS2i0WaE7NsHJ5vNb5f9rspNM1WNRI8xOgDXQUjAoMq"
    b"RAS4rRbCttleXcWeeZLRDy8QDkm9MT6s1y/V7/zsyW6N/DTMjEBhFPbmwBeCytoa5t6nSH/w"
    b"ESEZJFnuBbz42vG1wlSy+t3FJW79WEYyLSTT4t7NP7F9nw19hOTCMaR2jZACUif6DuDU/Cn2"
    b"9Ie5e7PEN18sc30lhhbVMOI62uJlNtc/5fDWEiGniL9/ESms9QIq1QpGJMWJk4d44ejzbNWb"
    b"CCETiw/QatT45dd3GVITaDMKjd/P4DafE4Df85U7tjQ1xHAyxkhqgH4V9iTi7Dv9Fb+t1nDL"
    b"14gV+jgoL2nZGKmuA901RPnvf5s3SjeCANkRgB+AEI9KUmLcT56ldPG90BsiUOeeHdPmCsYr"
    b"XcCRI2nz1TdPH/r8s0/i9N7VLkXciUE/5VV++Lg9+/r+Umtf438yITEwJvx/5AAAAABJRU5E"
    b"rkJggg==")
index.append('findnext')
catalog['findnext'] = findnext

#----------------------------------------------------------------------
frame = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAHhJ"
    b"REFUOI3tkzEKhEAUQ1/+zK1dUWT2ZC56rG8xiIKg+7U1TZokpEgkSzyBylD8rrntO2WApm2Q"
    b"vpcG96qrLGQJA/4y73V7fV6To5A+ALXBivk3hxiAMhR3d5/GKcSAy9IWEA05BLwN7jfIdRQK"
    b"D2kb1MM32rXkHAss9IUYpp5t/QAAAABJRU5ErkJggg==")
index.append('frame')
catalog['frame'] = frame

#----------------------------------------------------------------------
images = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAylJ"
    b"REFUOI1lk11oWwUAhb/7k581XfqXNF1tunbVLVVr7ag4ZVrrNsaQbiJaZKBDmRWLoi8b+jSK"
    b"MPVBQV8UXwT1xfmDLXMZVijinNrJOqzdZtquadIuTdI2aXZzf3Jv7vVBmJqdx4/DgQPnCFQo"
    b"ej5+PNzkOyYJwk3mAKYlUCgaxGLXxhIz4y+MjIzYAHJlgOz1+TvbGgJCBb9hQCKl0HV35HmP"
    b"16XCyCsAYmUASz/rzi0QRBFEUaCxzsPeh3e+/Pno5FsA0n9Np57CLWZmBr1uqzf96xfk539j"
    b"I3kV16ZqqmoD6JaLpVQGQ9fRTXZ3Pzjwb9HRAQarG+uHN3f19y4S8SFWs6PFhZ25Qj4Vpyrc"
    b"Q/jxEyzlbObnFlE0i3Q2YwoApw9xsnXvwBudh9/morqN937yUJag20zy7D6Vufg0N858jGD7"
    b"2HH0U5azKiWjxJXY/IY0OsBQ/faOd5xNNd+rid8zq+Wq8JtnAly6DG1alKmmT5iouobZ2kEk"
    b"Nsvs1RkCXQdwy5BdyxvS0L7gV3Wd93gvfnZ2KPHHdHxX35ZDnSGDbmeS1x7NcTL1JRPajwTT"
    b"RV7t3c/k6VOE7h/E568nlU4bsi8UaLnrycdkX430tSg40paQyDMtv0BEB1Pg3dUI55d9HLSa"
    b"cDfEqHVraNk4weatuEQJeenPhfHgufED7fdtDyCUYGURNAVKGhgaexydPQtNlL0PUfgrCsUN"
    b"cGzcbgFREpDzBf3IxAffHvTfVnO0py+ya1tH3T8mQwW9SNkqsh69TmAxQVZMkt5p097YjAgI"
    b"goA0Noc6tsBUv9/45vL0cri5Qe6q8QOKArqOYOkoSoHVdI5Mi0Wi9XbufeJ1JFEmnrxu3Fzi"
    b"8DlyhsLweDR2yczlwNZAKyIUVEI9Zba+WGY+CO19Q3h9XsAGxP8v8YcUxgN3BNs21tXdm0s5"
    b"3JaGpFnkCw7fTcFaaz+PvPQ+luUgCiLx5Ipxy5nufO4js71e58LZD3HSs7iwWTO91O0/zNNH"
    b"TiB6PGiqjccl4pIkT+XpiF5IHy/p68dKSgFFUSiXQZJdVNcGKZsGhq5jOw6SKLG8ki38DbMJ"
    b"XHT2R43dAAAAAElFTkSuQmCC")
index.append('images')
catalog['images'] = images

#----------------------------------------------------------------------
inspect = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAp9J"
    b"REFUOI3Fk+tLk1Ecx79ne+Yed2tuc8vlLTJF1HlJcoqaaEZaJHQjsIJAqBdlQr0JohDqVVGZ"
    b"78JukHTRl0mYUEpleWFD0OVyCtN5mc+e5Ww3t7WnN3tirD+gL/zg/M7ly+d3fucA/1skcYLj"
    b"uLIHd9/0OFbspZFIFKyLASUSWy623y4pLyfhxP3C+KS6+lCK/xdZqKkzqNUpYq/danWbJ8xs"
    b"Tr5h5/vBlzeNlU29ZvOIO/4MFZ8U5le47bYp5+nWZkW6Ji0SmKZnRZodrom3H5ZzG/YUOZnF"
    b"uURqnoB0XLp3/OvwO+OJA61MyA025IsE7JbVFXbZ48lS5vnMpuFwzeEjGYaiKurb2OAIAC6e"
    b"gJJK5V0bqy7vjwFmxiZkQ5BEWUoe2fQEWY+YStaVZ9ZzTsdi3ja15jKAWwC2AEAQMxBvBX1p"
    b"almalxAq/DsS3WCdLtvo5JfPNmba5AttzhFQDLu25iksqJADSOJL4A2ENC3r9wR/0kKBICIg"
    b"glASJfJxhLBBzrtOU8kbhGDLUFIi02/PHI+/O37APe7p7JZSyl6Xb02ilab75GK10qhv0AHR"
    b"CEegHF0Y2jVw/VmqsbL+Al9/PEF41bXEtJxqm31lerh33edQyZLkegWdUqQQq4q/r0/uO3Oj"
    b"pdZinZ8am/xoA/D3PfAtEQJIBZB5paPrqnXaXG8ZH3fQAklArlPI+ode5LgtT+cNKlKQcfT+"
    b"boeDsfMm8T2VANDFAgcbT5bptFKtP+R39fW9NgEQtjdnn23eX9s266GzOjofLSJBAgBSABkA"
    b"DAAqAFQBMAIoBZANQHbtWE73nfO13NLMp6ZEAnAcRwghIgB0LIQAogCCAAIxbK61SvNEn5V7"
    b"Tq9Vdf3zmRKIeEUTFxuLNc89/nDdH/xlAzHUigZXAAAAAElFTkSuQmCC")
index.append('inspect')
catalog['inspect'] = inspect

#----------------------------------------------------------------------
layout = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAZ1J"
    b"REFUOI2lkrFrFEEYxX+zHBE0G9BCRBCVJIqdoI0YK5FUgkXSaor8AynSWQhWtqkEtbHTRiwO"
    b"q5QprzHgoSSQFBaKJIGA2b2Z73sWu7e3ASMJPphi2J03v/fmg/9UAHi80lsKcJkQZoBbyAUh"
    b"4CLLAlkAd8eS9sY6bFy/NHEbF8tzNwIAT1Z6r3RCvXj/RQAdAAXuAbxZ22nQ9A/sxbvn6G/v"
    b"lY0BxoXhx+nzp6ps4e+Hv/4oASiKwdiIQDo9vPXbz/JY5ck9jAjcO0O048rNaRFUrzH/bJXC"
    b"HRd0nz/g4etZ8jzH3ZtlZnxY6CK3loFXbr8OIvdvXqTb+w5Ano8zNXmFOiaS83m9X+1TZZBV"
    b"BlXn+4URJX6XCQAzJ3C4zWRWp04jglATlGXkIBpWxPonRxIgkJCE1TcrDVoRWq+u1gCkZLis"
    b"ieAS5sN9i8CjiXqsP61tNQb5+Bk2NreJMTKIEUtGFjLq3kaTaO5bwNX1l48O5X07946jJNdu"
    b"Y4Dp4/zT1WuO7gTXWfcEcuSGPIEMNX24QPsKWf9I95PoDxEAIhVEfbTGAAAAAElFTkSuQmCC")
index.append('layout')
catalog['layout'] = layout

#----------------------------------------------------------------------
miscellaneous = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAklJ"
    b"REFUOI21kklIVXEUxn//+67ac0LNCQcUSpMCUxdRhhLWQl0k4qoBMV0kiGATEVSrCNq1iEAN"
    b"sxZtkiipwLICtQg0DC2TJIee+nJKvW9S37vvtEglrKCIPjir7/w45/Ad+N/Sq+y7NpX3nf17"
    b"skKSa14tSYNDpNEpEn6459Yfs1FlNyoPDIkcGRY5ulrloyJRlbaOnzb85dpmoN4eBOEfwPAB"
    b"AmmRkH8lKe9+024rvPas9Wo/glLCPsfp1BHd5/digJEIOTrszYDEBHjwBbjbm/fTRCkk3Gwo"
    b"dcrwU5GhJ9J86qSflyJ0iWR2i1i6RFSnCC9E6uWa6NeT69ZYy3JVRIul9tJtFZEQyOwEzNrI"
    b"Sg1SMy2f6E7OJkZgygC8kHKvk4yCj+TszCh8mzKW7H1otCp3dewj654dxQwMgx4KpsDiPMTF"
    b"c6gt39N37qrV3j5IVvUJrFoISgO/8jNp2um/3HdGc7lNmFmE2BiwfQanE4qOQVYh6dONb/Tw"
    b"4tH5mmzs5iSP3z+nbbADp25QEJWPZUHF6Y5lIXrO9f2g9AyQEOjvhrkxPB5BaSvLzAQwyAi5"
    b"aTk4zRWcC8vU25vB60Ovffb1YuvmsGLN6wUPMDcBIqAUbpepjQ7Zeom0bENpjLvmsLntiPhB"
    b"QYDPjwJICmLrQFnCUFiAArvBtFdjf4dx550pxwGntS725tJ2VZEYFse4YwqlFJYew+Zrchet"
    b"RxkK0YOlqVISrHUC8RujDjwYfH5LY64EX4h2E0jRRn891t8Zq8rc+Hz/rG+GvgB5gkbPfgAA"
    b"AABJRU5ErkJggg==")
index.append('miscellaneous')
catalog['miscellaneous'] = miscellaneous

#----------------------------------------------------------------------
modifiedexists = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAAAkAAAAOCAYAAAD9lDaoAAAABHNCSVQICAgIfAhkiAAAAWFJ"
    b"REFUKJFlkEsrhGEYhq/3fT9jxviM6TOnnEJW4gcgKX6AJhuUhYWyIAt7+Q0KS0OWsrWxUVYk"
    b"hySNxkyGkZzGZ2GQxwKD3PWsnqvuuwulDd9X4pRKsDssxLRMzExK8ae0AWB4dkQC8QjnJseZ"
    b"m0FtvtC+08rc/ILSALUNNdI82EJ51KaypAK7MQD1huWVZQA0gCjhxJxxzCm3T3dkuODxIk+8"
    b"Lw6ABeAv85PMJnEbCpg3yOPyvH1FYmlfFSFtNLn3a96zcBvL4+yW464+8h0N4PP7MPcK77VF"
    b"KB3ASdlE7PBfyAk6GFfxVnjFysLNRo7B/oEiVFQQ6olKsCOMu/dA6DLAwc6h+qG+hI1OjwlN"
    b"ljhtYfktWGnzWWc6vOKZchhaH8W7VYfV7hN+RQP0dvaQTCVJPWXwpBU1kWompsblz6ZoS0y8"
    b"iRj3lS72kQdrsUB67fT/Jl9VmVBnxOmK/tv0AbSrcOMtNiLbAAAAAElFTkSuQmCC")
index.append('modifiedexists')
catalog['modifiedexists'] = modifiedexists

#----------------------------------------------------------------------
morecontrols = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAp1J"
    b"REFUOI2F0jFLG2Ecx/HvPXeJUROiPUmgmA4FqUUdpBTEaNFJHaSLxfQVuPQNFNpRhAwuvoAu"
    b"Qk86OJQSBUVXaUkrImjFOKjxSkIaNNE8591zHWyN6eJvffh/+D/P89Msy/K5Jz+/fkVkMvia"
    b"hhof58nz57dnBkBHRweFQoH29nYMw2BlZYVMJsPl5SXlcpmA4/D53TvwPCbn5ijMz5NIJEin"
    b"02iWZfmjo6NUKhVc10UpRa1WQ0qJ67pIKclubjKq6/iuy5py6RkYpK2tjXw+f7NBLBYjFos1"
    b"rF2pVAAQQlDOHeH/+I7vXtP3LMSLkRF0XSeXy90Ad3N+fk6pVOLL4CAPe3vxpMTzfUgkENfX"
    b"eJ9KbHx8iVKK82y2ESgWi+TzeZqamojF4/R2dSGkhFqNy1IJ3/N4Gm3H9X1c36cajdYBKSXb"
    b"29vous7Z2Rkr+/usHR3hui5etcqb/n5wHD58+0YgEkHXNH79/l0H9vb22NraQgjB8fExlYkJ"
    b"9k5OODw8xK9Webu/D75P9/v3vJqZIRwOs7y8XAdOT0+xLItEIoFt29i2TbFYxHEcOoAH/f1o"
    b"SuFcXWEYBkKIeg8ATNPk4OCAnZ0dhBAopQAIBoO0GAbbuRxC19GEQNO0RsDzPPr6+piammJx"
    b"cRGlFIFAgGg0immadD1+zMdwmPGxMV5PTiKlpLm5uQ5omoZhGKTTaWzbZn19HdM0icfjhEIh"
    b"CqUSA8kkKhxmbWOj4duNf2VRSmEYBrOzswwPD7O7uwtAJBIhmUwyNDRENptlenoagKWlJVKp"
    b"VLihB62trXR3d9PT04OUEsdxaGlpIRgMcnFxAUC5XGZ1dZVUKhUC5C0QCoX4H7ubf4/2d1hr"
    b"uMLCwsKZ4zjXnZ2dj7gnd4cB/gA1hCWaJRLM3gAAAABJRU5ErkJggg==")
index.append('morecontrols')
catalog['morecontrols'] = morecontrols

#----------------------------------------------------------------------
moredialog = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAaJJ"
    b"REFUOI3VksFLG1EQxn8vu4poK1KtYFhCscaDpVpKLyu59D9oi+A/UDS5e4uKSDx59yJaj3rw"
    b"Li20h4Tdg5deSpMSQnJoS1vUGoiaxed4cdeNrujV7zK8mfd9880wBneA8dJ425t+uNX5uiPT"
    b"rJ/+kd9S9Gsqt5iT2wRKP0uMvn+GFs339RLJ+DAAs/OzygTIzmVRaulGgY5+TXLKQ4tma1tz"
    b"/DeLUgoAE7iB7PkmwdAc6X9o0ShDo9SC/6nLBBDJXqM/WbV4Zb0gpoR2ATHbENG8WftPgwLV"
    b"2hDls9ovM0xyCy52ysYtuDzt7Wc8OQgxj1Ma7B3tI6J5PtyDp4WRxCN2vnndZhTZTtnsTpep"
    b"fj3k5PiEZqzJxGQC4YzVDy59D/qoVCpgsk9uMSc+nLwTGWeWZiRd7pJ0uVNWNlfEyTsCSLDE"
    b"KAfhGE/Eae8ZAwXFH0Uyk5nLucMOwgACB8sby/LusyUTXyzhMS0OAoGrtoHgXW/U5aP7SaoH"
    b"NRmwBoJ6ywh2yg6O4+pYUXkfsXBSRHDyThD9HUTlfVxcYmuH+4VzlkEmgUrj7QoAAAAASUVO"
    b"RK5CYII=")
index.append('moredialog')
catalog['moredialog'] = moredialog

#----------------------------------------------------------------------
overview = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAkVJ"
    b"REFUOI19kUlMU1EUhr/7+mj7Sm1BSgsU4hCDgQ0JjhCTJiQu3NVEo7KRVdW4dOfClSv2sjBd"
    b"uHGjiUMwURwaIhICCBEhQashDGppqbQQOtE3uKCQloJ/cnPucP7/nP9cQQGhUCin63qePSCE"
    b"MEWj0Ynu7u5LwHJZgt1uv6iqqrHfymQyRjgcNoLB4BjgKOZKhWjsVbkYqVSKnp6eU319fW8A"
    b"126B/0KWZVRVJR6PEwgEOnp7e/uBOgBRsOBPJpPPtwnL8TWevJ5kJZHGwKDGodBcb8LrqULT"
    b"NKqrq/H5fDcikchDubiSYRh8GJllaCrGdX8nRxsUMpsGv1eyPHoxwmkZzne2oigKQghTmYXV"
    b"tTQvhxY40dbM8JdFUuk80z+iDE7M09l+nLfjMZIbuVJ7xYf+wRmEcpB344vYbRXEXn1nfSPH"
    b"ylqWgdEl5iNpnr2f4fa1c3sLTP2MM/3HQl7VqHdXcudKGwMTvwg++IyWzyNJJr7Ore7fgcks"
    b"MxfPIoBwdJVvkQ00IIeMcsAKQIV5y7Wu65TNoKPFg2QxY7ZacToqMVfIWGUJZ5UdxWZFViyc"
    b"aXHv30HXycO0f/pLQtThtmk4LYKmGoXWJgcpoxK7HuPC2SMlAhKApmmFtjTu+t14s2M01lbx"
    b"dCRDaFZwrNGDd3OSe34XQmx99zanpANd1/HW13L/Vhcfh0dZWlhHSIJ2jwPfTR82mw3DMHb8"
    b"lwm4XK6dx6uXG0qES4ZtMu3sRSEe8ng8Ab0oczep6F4AJBKJx8DsP7f3ACwAunutAAAAAElF"
    b"TkSuQmCC")
index.append('overview')
catalog['overview'] = overview

#----------------------------------------------------------------------
process = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAA2pJ"
    b"REFUOI11k11oWwUYht/zl5NzcpaTk98lNI1JOc2kbbqxYqpTx2y6Ib2Y28hovRFkbFi88CLi"
    b"TWWgFVRkFnH4AxWcd4PBmBtM98Na0+ykFdKltN3SLMsMC5u1PelfTtrkpF7YyhT9bt/vfS4+"
    b"vgf4n2lrO/pVd/fgitkc6LNa/d3R6Md3+/uHbgGwP71H/FdZlqNnZTncL4ocaNoAQTDB4dgB"
    b"j8eBROKnxLlzp48BePwPAMNIrXv3vv6DptVIq9UbCgScEEUBgmACxxnBMBSampzQdQax2Hs3"
    b"8/lLPQDWqW1Aa2vfNUFobHe7na7jx19GJLIbsuwBz3PQ9Tp4ngVJEiAIwGDgbJnMxNj6+tqD"
    b"vwGS1PpWIOB3nTx5CDabGYqSQzx+D4qShtttQUODHRRFwmrl0dX1HEtRjS+Mj98aoQDA5+v+"
    b"Yteu51/t7d1PmUw8rl+fRSIxXk2nlfvx+NnY8nKV3rfvlWZRZMFxNESRxeamYIvHx5boUOjY"
    b"18Fg1ymvV0Jjox03btxFKjVVHRv77rO1td8uAkhr2mqIYRhYLH/dolgsgaLq6OzsjdHBYOSU"
    b"wyHA53NBVTVMTWUwOvrNkKYVzgNIS5Iv3Nf35tGdOzkwDIlCQcXs7CMUiypKJVUjS6UHv7As"
    b"C12vY2mpDFUtQdMKSQCTZnNDx8DAt1d7el7yWSwG1Go6ZmYeYXIyB0WZWFWU4Q/I0dHvTwMk"
    b"eJ7DxoYOSdpRYVm7LRzu/XRg4MvLBw92mAmiCkFg4fGIWF4uI5OZWcpmL3xULhev0LLcErRY"
    b"eLAsDY5jcPjwi7Tff2YwEtnvcDqNMJkIGI0mWCwcdH0TLEtgbu7KcKmUuwSgSEWjb3/S0hLy"
    b"u1wCGIaCKPJke3vQZLcbQNMEKpUqbDYTarU6RkayqNdpzM9XrA8fjg8DWKAmJn7+kedd4ebm"
    b"0DM0TcDlEsFxJGiaxNzc70gmc0ilClhc3MCTJ6tIpXKYnk5rCwtT5wGo26/s2LPnjYuyvLvz"
    b"xIlD9Y4OmZ6eLuD27fu4cyeHTOaeJor0Y1VdJMvlCpHPXx3StD8uA8g/JRPbZDQ6XvN63cZY"
    b"7PNBSTIjkZhFMvnrWjZ74cP5+dw1ALUtf8pbMq38W0QDAN7pbHvnyJEzKwcOvL/I8653ATwL"
    b"QNrKDQDo7cKfzfc7KseZc4UAAAAASUVORK5CYII=")
index.append('process')
catalog['process'] = process

#----------------------------------------------------------------------
pyshell = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAg5J"
    b"REFUOI2tkk1I03EYxz+//1+2Of9L52r24uYaBSXdutShlDp0CYzohbpY0cFDL3gWi7oUQmAl"
    b"QUJ18mAzmNjBoiDQELwoxWa25Qs5TciJNcZ0//+eLmrOF4roOT2/5/s83+/z8oP/aZebmsQX"
    b"CuUex2Lib2sToP1PNdoKv86f+inHu7qU0dvLpoYGOsPhM39PENxZd/LiJbW5upr32QUGIxHu"
    b"fpsS2/UrAtg2IlAAmsuVLOnvdxfriozA95kktnQaezqFVrmP2arDWIlJtWEHnndv3Ps/DzOj"
    b"6xgTCey6RuZGI5mWR1imhZjmerWS99oDosE0EDXankhZX49UfB0Xd/dLAQIrcx1HDonn/p3f"
    b"BHtLS+VBMLgc8L7tloovMfF8GBTN7xvIU3I6Q+6nrWv2IsDYoj9WNhQVfzwmRvM9AcqXF1bs"
    b"el0+OWGpkpLn680EgLu1RQIjcfEORQVNhVdiWzpfiLP+at7sWn45z4qqjqJrimxfD+TkRB4a"
    b"8OGqrQW4sFZaqdtbPw7kdo2PyI54XIDI6hTd650Oxj+J4+xpWRIvWMSMwvprjXangUIx392B"
    b"7eCBSmUU5Z/KNJmfGMV96yZT7aHdwHDBMriQYd6yyClFYc05CmvOw6r7iwhZy2TuYTNAAhZ/"
    b"4lIXuIwOtm87BlDsK2cuOYNud2DN/gCxIGvCyOgr4BSQWruHf7BfnoPGjBi/kJoAAAAASUVO"
    b"RK5CYII=")
index.append('pyshell')
catalog['pyshell'] = pyshell

#----------------------------------------------------------------------
recent = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAUBJ"
    b"REFUOI3t0j1rUwEUxvHfTW9rIHfRpd1cVBxc1MHsOhecHRXLLUVwMZ/AIXERQe4iCDppB8Gt"
    b"Szct6AeILYKm+BKHXN9SE4K9xyFa7ezaBw6c4TmH/3nhQEl03ESOAhPkwkPkEh/wFW8lCpVj"
    b"oKaukqspREcZozLi0YWIjn4M+9N8MowotyI+vox4tRpxO4tYuzqNtm4MuhF3FyIV6tI6i4+5"
    b"cyQzl7FwlsmQeyc+mcvmLfU4vcLR81Pu8ZeTZjN2+u9SVKJic5Vmq7E3XP0wV7bmjQa8fsqZ"
    b"FX6OmTnEuRaDLnTTvYK1pR3Xyr8Nxp+nBLyRzDRd/8H2OpPvHL/I/VNQ1Pat9EWb2cZ+gksb"
    b"TdXuSOzyrcf7Z9RSyk3JDU+SaLv1zxUaErlQSFxGDwPh+W/PA1R/PEnL8v8/woH8Ah0VioYI"
    b"i9+mAAAAAElFTkSuQmCC")
index.append('recent')
catalog['recent'] = recent

#----------------------------------------------------------------------
saveperspective = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAA1FJ"
    b"REFUOI1tk21MU3cUxp97WwqVS1tx0mLvaKtrYUB94SbjRaUms8bICg1RXGVQZgwuTRYTY9Rt"
    b"H5bgB8eWJbo4k82Ixrg4om4TMjuXofgWgcGQzW3oWlrWW0opb6Ug9NLy3xdrkHk+nl+eJ+fk"
    b"PEeEl5TD4WBMJlMbgLU+n68NwEKC2e12hdls/qSubt9Ft3sgm36ZQSAQ2rR9e1lJcckWB4DV"
    b"i5lKpTx+5MhHB+Ry9YpgMPh/g6qqqqK3bdWX4gugKcGXtEbDHkywmpoaQ17e+uq7937FiRPH"
    b"Z8bGRhpEi8W1tbWlFdZdTrksXT4R6MZ7jkrKmM9yvb0Daes3cEM7dpTf6enpU3xw9OD1wUHX"
    b"YQA/UQmxzWYzWa27WhgmXRYOdqC8YhNSGRVApnDt++sLvf3iWd4fSDl/7tTX8XjckdCJno1m"
    b"sliqWhhGIRvx/oK3LEVIU4gQnxnH/a4xiKUsRcWmJU1nTj6amHpqWTy1qL6+vtJSvvu7ZakM"
    b"M+q9jWx9OhixBJ2nnXAPzSGarkNf9yNsLlyBsq25K/sfPsnkQ1M/PjfQ6XT2ybCweWHqW7p6"
    b"pwrK18zw97pBBiKYfPgPXP7HqHhnI4RoEvKNORSXv5LrevAHG5x42ppYoaO15XIr7x9VFL4R"
    b"zaH4MDXaHYOWVUJwOvFvextyayth0EowO0PjVcPrFKeXFXj/fqLxBKeviUKhkADAPzI6dznW"
    b"Gd1XrN8o176yCp6ms3DNj0NdtxdqHcFyaQCDvgguOYPgCrTYWqzZ0PXgd70YAD4GxDINe8P6"
    b"4TE2Iy0V/BefgZ/mEW04A7YgC6zkL0TCEbCaLKz2/gZCa0CEOczH45zIDqRk6rTt7371ZalS"
    b"SlMTpz/HnZ4+nJelRLVqCb2NW0VNDvO42A7I4UXptjy4e/ph29/o+ZOP1KBBldE0dPUbEnNe"
    b"IeNlheSGSkpykpN9AN7UyunDraf2zgvDLeRm8yESfnyWdP3QSAwZjAdALgCgc49VID83k1hl"
    b"CbmlTCbrkpICAAoTZ1JK8f6VT/cIZLaddFw9RrIzlrkAGJ4H4eSazGG/2UiaVVJiENEuANzS"
    b"/1Az2N9YXzRnzFJ4AOhfgDlAkRG4KaeoCwDUS8WLImsGsHZp/z+rvEoNBUEjtAAAAABJRU5E"
    b"rkJggg==")
index.append('saveperspective')
catalog['saveperspective'] = saveperspective

#----------------------------------------------------------------------
customcontrol = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAnFJ"
    b"REFUOI2lkz2LlGcUhq/zPO/M7M7OTtaJu7K76kaIaKHiF341miqkCcTKdCkCAZv8AklnYyCE"
    b"/IJU2vgDRLTSWIghqPiBijDqiBtdM7uTmffrnGPxjiJCIODdHLjhuTj34X7gIyWLe86cOXTg"
    b"wPfmpZQlqApqoArFeGpB5VnlmQbSXL17+9fTyfbP1n118sSWmcEwZ5RBmsl4QlZAmsIogyyH"
    b"USqMCiiKwMqa8fzx/NGkNVPLFucbqNUxAzNAhAjkpeMmpKWjFjBz1AT3QK4JT+4mZVKrRRbm"
    b"W0y3m+9yvfin4Gq3YP9Sg2Hh7J1LAAc33B2AvIi0p4QEYOwBcOVRyo2e8kqFS/eWqU9McHip"
    b"ya5ZYetcIC8M9yqelmUFeF+X7/RZbrSor7zi5f0uT/ol1xY3s2/bBn45FnEBNa+iooT3H68M"
    b"lG7WYOOnkxw/OMfZU0f47eReFhrOlZ7y8/USLRXcMTVcPwAEgcs3e1x78JpRrUEQZ9/nTX78"
    b"chPr17V43De0NMwqgOEVQEQA+KQZ+f3bjXRqgYcDuPg00H3tTE0Fts0KVktYHni1gTuokkSE"
    b"GGPVKoFOu8a9Xp9HL4fs3zLN6tY2a5nTDhl/PHhO3LkeVRsfXqsjhlglcXeWOnW+2zkBqjzL"
    b"RjRtggt/LTMzM81PX3ToNCEtDDOpADGJ0qi/3UBoTQZ+ODYLppz7c0BIc77ePk1/VLJn0yRm"
    b"RhKdEAJEkaS/msvKmhAjaFk10VQxdw7NN8GURALukf5aiZkhAsNRxr+rwyixteObhc27jwdx"
    b"MX3bKEOBCKjmgI47XoIXgFIUBX/3bp3////2P/QGWsxIJsvdP+sAAAAASUVORK5CYII=")
index.append('customcontrol')
catalog['customcontrol'] = customcontrol

#----------------------------------------------------------------------
deletedocs = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QAAAAAAAD5Q7t/AAAA"
    b"CXBIWXMAAA3WAAAN1gGQb3mcAAACTUlEQVQ4y82SPUxTURTH/6f3fb9a2tDSIqSPhIogMSom"
    b"TNVB487o4qCLm0bdJEad1MnNxN1FIw6ExagkJn4UURI+JA0fBQyg0DxqGyTl9r17HbBAkcXN"
    b"311ucs755fxvLmEPzwdeQ4UAh1InIDuEkCd8ITqFkAc5598Wl5bvElC4feMyAECpDva/eo9A"
    b"gAIVz++sCNEjhTwnheiQQFjTNMUyDORdt+S6a88URf1QnVMA4OHjJxgbn2CtqdQ1xth1IWWC"
    b"iMg0DUQjITQnouCco7iWH3fz3/O2bW9vzADAh8TsTDbqCXogibVpmk6hoIloOIiQrQPCh/Ar"
    b"En7lDfzy23t3eguF0jqGMh9BAHD0ZDeE8NONTU5/On06crgtBcvQEI9GkIjHIaSE73lQFQbO"
    b"eYaIzuu6vpBMJrciEAGln2sjXd2nBtoPtV5ItTRjcmoGRECl4qFcLoMpCgzThmHoLGTpqHmD"
    b"Rqcd6bM9G1LwpdFsDosrLlqcJBoSCdiGinAoCMuyMJbNYXAwM9J79dLCxSu3AAABAJBSgogA"
    b"CQSYivpYAqZlgbEAgsEgwnV1W/UtJAB4vtgR7EXW3KunlqpwX8G/8L8IJPZJ+Te0O/xuwdzU"
    b"KB7dv4lyeUMlItS2/Gkkgud5KBULKhGxL+9eAsDOR9JtU8lNT46pmpaL1UecyAGLCSEgfAHO"
    b"OX6srIoXfU/l8OfhziPHu1oYo9ltQfHXOhBr8qazE32lYmF2dWn+jOM4xxrjDTHbMuF7FXdu"
    b"fv7r0KfMMt/cXFYUZaW62W+bkO7zu6lNiAAAACJ6VFh0U29mdHdhcmUAAHjaKy8v18vMyy5O"
    b"TixI1csvSgcANtgGWBBTylwAAAAASUVORK5CYII=")
index.append('deletedocs')
catalog['deletedocs'] = deletedocs

#----------------------------------------------------------------------
