# Generated by Django 3.2.5 on 2022-01-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benutzer', '0002_historicalbenutzer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benutzer',
            options={'permissions': [('berechtigung', 'Berechtigung')], 'verbose_name': 'Benutzer', 'verbose_name_plural': 'Benutzer'},
        ),
        migrations.AlterField(
            model_name='benutzer',
            name='email',
            field=models.EmailField(blank=True, db_column='bnz_email', default='', max_length=128, verbose_name='E-Post-Adresse'),
        ),
        migrations.AlterField(
            model_name='historicalbenutzer',
            name='email',
            field=models.EmailField(blank=True, db_column='bnz_email', default='', max_length=128, verbose_name='E-Post-Adresse'),
        ),
    ]
